// <copyright file="OperationType.cs" company="APIMatic">
// ApimaticCalculator.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ApimaticCalculator.Standard.Models
{
    /// <summary>
    /// OperationType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OperationType
    {
        /// <summary>
        /// Sum.
        /// </summary>
        [EnumMember(Value = "SUM")]
        Sum,

        /// <summary>
        /// Subtract.
        /// </summary>
        [EnumMember(Value = "SUBTRACT")]
        Subtract,

        /// <summary>
        /// Multiply.
        /// </summary>
        [EnumMember(Value = "MULTIPLY")]
        Multiply,

        /// <summary>
        /// Divide.
        /// </summary>
        [EnumMember(Value = "DIVIDE")]
        Divide
    }
}