// <copyright file="IHttpClientConfiguration.cs" company="APIMatic">
// ApimaticCalculator.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Http.Configuration;

namespace ApimaticCalculator.Standard.Http.Client
{
    /// <summary>
    /// Represents the current state of the Http Client.
    /// </summary>
    public interface IHttpClientConfiguration : ICoreHttpClientConfiguration { }
}